[tool.poetry]
name = "fedotllm"
version = "0.1.0"
description = "LLM-based prototype for nexgen AutoML"
authors = ["Alexey Lapin <a.lapin@itmo.ru>"]
license = "BSD 3-Clause"
readme = "README.md"
packages = [
    { include = "fedotllm", from = "libs" }
]

[tool.poetry.urls]
repository = "https://github.com/aimclub/FEDOT.LLM"

[tool.poetry.dependencies]
python = "~3.10.0"

# Fedot
fedot = "^0.7.5"
giotto-tda = "^0.6.0"
ripser = "^0.6.4"
protobuf = "^5.29.0"
opencv-python = "^4.11.0"
pillow = "^11.1.0"
tensorflow = "^2.18.0"
tensorflow-io-gcs-filesystem = "^0.31.0"

# Data processing
pandas = "^2.2.3"
tabulate = "^0.9.0"

# LangChain ecosystem
langchain = "^0.3.10"
langchain-core = "^0.3.22"
langchain-community = "^0.3.10"
langchain-openai = "^0.2.11"
langgraph = "^0.2.56"
langchain-text-splitters = "^0.3.2"

# Web Interface
streamlit = "^1.40.2"
streamlit-extras = "^0.5.0"
gradio = "^5.8.0"

# Database and Vector Store
chromadb = "^0.5.23"

# Utilities
typing-extensions = "^4.12.2"
pydantic = "^2.10.3"
asyncio = "^3.4.3"
ipython = "^8.30.0"
graphviz = "^0.20.3"
beautifulsoup4 = "^4.12.3"
dynaconf = "^3.2.6"
watchdog = "^6.0.0"
loguru = "^0.7.3"
autoflake = "^2.3.1"
requests = "^2.32.3"
tenacity = "^9.0.0"
fastapi = "^0.115.6"
tiktoken = "^0.8.0"
html2text = "^2024.2.26"
deep-translator = "^1.11.4"

[tool.poetry.group.dev.dependencies]
flake8 = "^6.1.0"
pytest = "^7.4.3"
ruff = "^0.8.2"
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
