[project]
name = "fedotllm"
version = "0.1.0"
description = "LLM-based prototype for nexgen AutoML"
authors = [{ name = "Alexey Lapin", email = "a.lapin@itmo.ru" }]
license = "BSD 3-Clause"
readme = "README.md"
requires-python = "~=3.10"
dependencies = [
    "autoflake>=2.3.1",
    "beautifulsoup4>=4.13.3",
    "chromadb>=0.6.3",
    "deep-translator>=1.11.4",
    "docstring-parser>=0.16",
    "dynaconf>=3.2.10",
    "fedot>=0.7.5",
    "giotto-tda==0.6.0",
    "graphviz>=0.20.3",
    "html2text>=2024.2.26",
    "hydra-core>=1.3.2",
    "instructor>=1.7.8",
    "json-repair>=0.40.0",
    "langchain-core>=0.3.49",
    "langchain-openai>=0.3.11",
    "langfuse>=2.60.2",
    "langgraph>=0.3.21",
    "litellm==1.64.1",
    "loguru>=0.7.3",
    "nbclient>=0.10.2",
    "pandas>=2.2.3",
    "pygwalker>=0.4.9.14",
    "setuptools>=78.1.0",
    "streamlit>=1.44.0",
    "streamlit-extras>=0.6.0",
    "tabulate>=0.9.0",
    "tenacity>=9.0.0",
    "tiktoken>=0.9.0",
    "typer>=0.15.2",
]

[project.optional-dependencies]
autogluon = []

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "mypy>=1.15.0",
    "pandas-stubs>=2.2.3.250308",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.26.0",
    "ruff>=0.11.2",
    "types-pyyaml>=6.0.12.20250402",
    "types-tqdm>=4.67.0.20250404",
]

[tool.ruff]
exclude = ["user_data/*", "test*", "fedotllm/**/templates/**", "examples"]

[tool.mypy]
exclude = '''(?x)(
    user_data/.*
    | test.*
    | fedotllm/agents/automl/templates/.*
    | examples/.*
)'''

[tool.pyright]
exclude = [
    "user_data/.*",
    "test.*",
    "fedotllm/agents/automl/templates/.*",
    "examples/.*",
]
