lclz = {
    'ru': {
        'MENU': 'Меню',
        'INIT_LLM_MODEL_HEADER': 'БЯМ',
        'LLM_NAME': 'Название БЯМ',
        'NAME': 'Имя',
        'NO_NAME': 'Не выбрана имя',
        'API_KEY': 'API Ключ',
        'BASE_URL': 'Базовый URL-адрес',
        'BASE_URL_HELP': 'Базовый URL-адрес для запросов к API. Указывайте только при использовании прокси-сервера или эмулятора сервиса.',
        'SUCCESS_MODEL_SET': 'Успешно выбрана БЯМ',
        'INIT_DATASET_HEADER': 'Файлы датасета',
        'CHOOSE_FILES': 'Выберите файлы',
        'FILES_PREVIEWS': 'Просмотр файлов',
        'PREVIEW': 'Предпросмотр',
        'GREETING_MSG': 'Привет! Выбери модель, загрузи файлы датасета и пришли мне описание задачи!',
        'CHAT_INPUT_PLACEHOLDER': 'Введите здесь описание задачи...',
        'NO_MODEL_AND_DATASET': 'Сначала выберите БЯМ и загрузите файлы датасета!',
        'NO_MODEL': 'Сначала выберите БЯМ!', 
        'NO_DATASET': 'Сначала загрузите файлы датасета!',
        'SPINNER_LABEL': 'Подождите...',
        'SUBMIT': 'Отправить',
        'RESULTS': 'Результаты'
    },
    'eng': {
        'MENU': 'Menu',
        'INIT_LLM_MODEL_HEADER' : 'LLM',
        'LLM_NAME': 'LLM Name',
        'NAME': 'Name',
        'NO_NAME': 'No name provided',
        'API_KEY': 'API Key',
        'BASE_URL': 'Base URL',
        'BASE_URL_HELP': 'Base URL for API requests. Only specify if using a proxy or service emulator.',
        'SUCCESS_MODEL_SET': 'Successfully set up an LLM',
        'INIT_DATASET_HEADER': 'Dataset Files',
        'CHOOSE_FILES': 'Choose files',
        'FILES_PREVIEWS': 'Files previews',
        'PREVIEW': 'Preview',
        'GREETING_MSG': 'Hello! Pick a model, upload the dataset files and send me the task description.',
        'CHAT_INPUT_PLACEHOLDER': 'Enter task task description here..',
        'NO_MODEL_AND_DATASET': 'Oh, you need to pick an LLM and upload dataset files first!',
        'NO_MODEL': 'Oh, you need to pick a model first!',
        'NO_DATASET': 'Oh, you need to upload the dataset files first!',
        'SPINNER_LABEL': 'Give me a moment...',
        'SUBMIT': 'Submit',
        "RESULTS": 'Results'
    }
}
