name: Pre-commit checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python 3.10
      run: uv python install 3.10

    - name: Install dependencies
      run: |
        uv sync --dev

    - name: Check code formatting with ruff
      run: |
        uv run ruff format --check .

    - name: Lint code with ruff
      run: |
        uv run ruff check .